# Spec: DM-001, FR-AI-002
"""RAGDocument model — pgvector embeddings for incident similarity search.

MVP scope: incident history embeddings only (source_type='incident').
Phase 2: extends to 'document', 'playbook', 'manual' source types.

Note: HNSW index on embedding column is created in Alembic migration,
not via SQLAlchemy (requires specific WITH parameters).
"""

from datetime import datetime
from uuid import UUID, uuid4

from pgvector.sqlalchemy import Vector
from sqlalchemy import DateTime, ForeignKey, Index, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDMixin


class RAGDocument(Base, UUIDMixin, TimestampMixin):
    """Vector embedding for RAG similarity search.

    Stores content text and its 384-dimensional embedding generated by
    sentence-transformers (all-MiniLM-L6-v2). Used to find similar past
    incidents and provide context to MTL RCA prompts.
    """

    __tablename__ = "rag_documents"

    source_type: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="incident",
        comment="MVP: 'incident' only. Phase 2: 'document', 'playbook', 'manual'",
    )
    source_id: Mapped[UUID] = mapped_column(
        ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False
    )
    content: Mapped[str] = mapped_column(
        Text, nullable=False, comment="Embedding source text"
    )
    metadata_: Mapped[dict] = mapped_column(
        "metadata", JSONB, nullable=False, server_default="{}",
        comment="instance_id, anomaly_type, severity, resolution, was_correct",
    )
    embedding = mapped_column(
        Vector(384), nullable=False,
        comment="sentence-transformers output (384 dim). Phase 2: 1536 (OpenAI)",
    )

    # --- Relationships ---
    incident: Mapped["Incident"] = relationship(  # noqa: F821
        back_populates="rag_documents"
    )

    __table_args__ = (
        Index("idx_rag_documents_source", "source_type", "source_id"),
        Index("idx_rag_documents_created", "created_at"),
        # HNSW index on embedding created in migration:
        # CREATE INDEX idx_rag_documents_embedding
        #     ON rag_documents USING hnsw (embedding vector_cosine_ops)
        #     WITH (m = 16, ef_construction = 64);
    )

    def __repr__(self) -> str:
        return f"<RAGDocument {self.source_type}:{self.source_id}>"
