# Spec: FS-AI-013
"""Tests for FS-AI-013 LLM Observability Acceptance Criteria.

Generated by: uv run python -m scripts.gen_spec_tests
Strategy: TEST-STRATEGY-001

All 7 ACs are covered with real assertions against the in-memory
LLMObservabilityService. No live LLM calls — all data is mock.
"""

from datetime import datetime, timedelta, timezone
from unittest.mock import MagicMock
from uuid import uuid4

import pytest

from tests.conftest import spec_ref

from app.schemas.llm_observability import (
    LLMCallRecord,
    LLMObservabilitySummary,
    ModelDriftResult,
)
from app.services.llm_observability import LLMObservabilityService, estimate_cost


# ---------------------------------------------------------------------------
# Auth override for API endpoint tests
# ---------------------------------------------------------------------------

def _setup_auth_override():
    """Override JWT auth with a mock super_admin user."""
    from app.api.deps import get_current_user
    from app.main import app as fastapi_app

    mock_user = MagicMock()
    mock_user.id = uuid4()
    mock_user.role = "super_admin"
    mock_user.is_active = True

    async def _override():
        return mock_user

    fastapi_app.dependency_overrides[get_current_user] = _override
    return get_current_user


def _teardown_auth_override(dep_key):
    from app.main import app as fastapi_app
    fastapi_app.dependency_overrides.pop(dep_key, None)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_service() -> LLMObservabilityService:
    """Create a fresh (non-singleton) service for isolated tests."""
    return LLMObservabilityService()


def _seed_records(
    svc: LLMObservabilityService,
    count: int = 5,
    *,
    model: str = "gpt-4o",
    provider: str = "openai",
    latency_ms: int = 1200,
    prompt_tokens: int = 500,
    completion_tokens: int = 200,
    has_hallucination: bool = False,
    is_correct: bool | None = None,
    base_time: datetime | None = None,
) -> list[LLMCallRecord]:
    """Insert *count* records and return them."""
    base = base_time or datetime.now(timezone.utc)
    records = []
    for i in range(count):
        r = svc.record_llm_call(
            provider=provider,
            model=model,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            latency_ms=latency_ms,
            has_hallucination=has_hallucination,
            is_correct=is_correct,
            timestamp=base + timedelta(seconds=i),
        )
        records.append(r)
    return records


# ---------------------------------------------------------------------------
# AC-1: All LLM calls are recorded with tokens / latency / cost
# ---------------------------------------------------------------------------


@spec_ref("FS-AI-013", "AC-1")
async def test_fs_ai_013_ac1_llm_llm_metrics():
    """FS-AI-013 AC-1: record_llm_call stores token/latency/cost data."""
    svc = _make_service()
    record = svc.record_llm_call(
        provider="openai",
        model="gpt-4o",
        prompt_tokens=100,
        completion_tokens=50,
        latency_ms=850,
    )

    assert svc.record_count == 1
    assert record.provider == "openai"
    assert record.model == "gpt-4o"
    assert record.prompt_tokens == 100
    assert record.completion_tokens == 50
    assert record.latency_ms == 850
    # Cost auto-calculated: 100*0.00001 + 50*0.00003 = 0.001 + 0.0015 = 0.0025
    assert record.cost == pytest.approx(0.0025, abs=1e-6)
    assert record.timestamp is not None


@spec_ref("FS-AI-013", "AC-1")
async def test_fs_ai_013_ac1_fifo_cap():
    """FS-AI-013 AC-1: In-memory storage is capped at 10,000 (FIFO)."""
    svc = _make_service()
    _seed_records(svc, count=10_001, latency_ms=100, prompt_tokens=10, completion_tokens=5)
    # Deque maxlen=10000 — oldest record evicted
    assert svc.record_count == 10_000


@spec_ref("FS-AI-013", "AC-1")
async def test_fs_ai_013_ac1_cost_estimation():
    """FS-AI-013 AC-1: estimate_cost returns correct values for known models."""
    # gpt-4o: input=0.00001, output=0.00003
    cost = estimate_cost("gpt-4o", 1000, 500)
    assert cost == pytest.approx(1000 * 0.00001 + 500 * 0.00003, abs=1e-8)

    # Offline model: zero cost
    cost_offline = estimate_cost("mistral:7b", 1000, 500)
    assert cost_offline == 0.0


# ---------------------------------------------------------------------------
# AC-2: GET /api/v1/llm-observability/summary returns aggregated data
# ---------------------------------------------------------------------------


@spec_ref("FS-AI-013", "AC-2")
async def test_fs_ai_013_ac2_get_api_v1_llm_observability_summary():
    """FS-AI-013 AC-2: get_summary returns correct aggregated data."""
    svc = _make_service()
    now = datetime.now(timezone.utc)
    _seed_records(
        svc,
        count=10,
        latency_ms=1000,
        prompt_tokens=200,
        completion_tokens=100,
        base_time=now - timedelta(minutes=5),
    )

    summary = svc.get_summary(
        from_ts=now - timedelta(hours=1),
        to_ts=now + timedelta(minutes=1),
    )

    assert isinstance(summary, LLMObservabilitySummary)
    assert summary.total_calls == 10
    assert summary.total_tokens == 10 * (200 + 100)  # 3000
    assert summary.avg_latency_ms == pytest.approx(1000.0)
    assert summary.total_cost > 0
    assert summary.hallucination_rate == 0.0


@spec_ref("FS-AI-013", "AC-2")
async def test_fs_ai_013_ac2_empty_summary():
    """FS-AI-013 AC-2: Empty service returns zeroed summary."""
    svc = _make_service()
    summary = svc.get_summary()
    assert summary.total_calls == 0
    assert summary.total_tokens == 0
    assert summary.avg_latency_ms == 0.0


@spec_ref("FS-AI-013", "AC-2")
async def test_fs_ai_013_ac2_api_endpoint(client):
    """FS-AI-013 AC-2: API endpoint returns valid JSON summary."""
    dep_key = _setup_auth_override()
    try:
        # Pre-record via API
        await client.post(
            "/api/v1/llm-observability/record",
            json={
                "provider": "openai",
                "model": "gpt-4o",
                "prompt_tokens": 300,
                "completion_tokens": 150,
                "latency_ms": 900,
            },
        )

        resp = await client.get("/api/v1/llm-observability/summary")
        assert resp.status_code == 200
        data = resp.json()
        assert "total_calls" in data
        assert "total_tokens" in data
        assert "avg_latency_ms" in data
        assert "hallucination_rate" in data
        assert data["total_calls"] >= 1
    finally:
        _teardown_auth_override(dep_key)


# ---------------------------------------------------------------------------
# AC-3: Hallucination flag is tracked and rate calculated
# ---------------------------------------------------------------------------


@spec_ref("FS-AI-013", "AC-3")
async def test_fs_ai_013_ac3_has_hallucination_true():
    """FS-AI-013 AC-3: has_hallucination flag is stored and hallucination_rate calculated."""
    svc = _make_service()
    now = datetime.now(timezone.utc)

    # 3 normal + 2 hallucinated = 40% hallucination rate
    _seed_records(svc, count=3, has_hallucination=False, base_time=now)
    _seed_records(
        svc,
        count=2,
        has_hallucination=True,
        base_time=now + timedelta(seconds=10),
    )

    summary = svc.get_summary()
    assert summary.total_calls == 5
    assert summary.hallucination_rate == pytest.approx(0.4, abs=0.01)


@spec_ref("FS-AI-013", "AC-3")
async def test_fs_ai_013_ac3_hallucination_record_field():
    """FS-AI-013 AC-3: Individual record preserves hallucination flag."""
    svc = _make_service()
    record = svc.record_llm_call(
        provider="openai",
        model="gpt-4o",
        prompt_tokens=100,
        completion_tokens=50,
        latency_ms=500,
        has_hallucination=True,
    )
    assert record.has_hallucination is True


# ---------------------------------------------------------------------------
# AC-4: Daily budget exceeded detection
# ---------------------------------------------------------------------------


@spec_ref("FS-AI-013", "AC-4")
async def test_fs_ai_013_ac4_offline_llm():
    """FS-AI-013 AC-4: check_daily_budget returns True when daily limit exceeded."""
    svc = _make_service()
    now = datetime.now(timezone.utc)

    # Record calls totaling 600 tokens (prompt=400 + completion=200)
    svc.record_llm_call(
        provider="openai",
        model="gpt-4o",
        prompt_tokens=400,
        completion_tokens=200,
        latency_ms=1000,
        timestamp=now,
    )

    # With limit=500 → exceeded (total=600)
    assert svc.check_daily_budget(daily_limit=500) is True
    # With limit=1000 → not exceeded
    assert svc.check_daily_budget(daily_limit=1000) is False


@spec_ref("FS-AI-013", "AC-4")
async def test_fs_ai_013_ac4_budget_ignores_old_records():
    """FS-AI-013 AC-4: Budget check only considers today's records."""
    svc = _make_service()
    yesterday = datetime.now(timezone.utc) - timedelta(days=1)

    # Old record (yesterday) — should not count
    svc.record_llm_call(
        provider="openai",
        model="gpt-4o",
        prompt_tokens=999_999,
        completion_tokens=999_999,
        latency_ms=100,
        timestamp=yesterday,
    )

    # Today: only 100 tokens
    svc.record_llm_call(
        provider="openai",
        model="gpt-4o",
        prompt_tokens=50,
        completion_tokens=50,
        latency_ms=100,
        timestamp=datetime.now(timezone.utc),
    )

    assert svc.check_daily_budget(daily_limit=500_000) is False


# ---------------------------------------------------------------------------
# AC-5: Weekly accuracy below 70% detection
# ---------------------------------------------------------------------------


@spec_ref("FS-AI-013", "AC-5")
async def test_fs_ai_013_ac5():
    """FS-AI-013 AC-5: check_weekly_accuracy returns True when accuracy < 70%."""
    svc = _make_service()
    now = datetime.now(timezone.utc)

    # 3 correct + 7 incorrect = 30% accuracy → below 70%
    for i in range(3):
        svc.record_llm_call(
            provider="openai", model="gpt-4o",
            prompt_tokens=100, completion_tokens=50, latency_ms=500,
            is_correct=True,
            timestamp=now - timedelta(days=1, seconds=-i),
        )
    for i in range(7):
        svc.record_llm_call(
            provider="openai", model="gpt-4o",
            prompt_tokens=100, completion_tokens=50, latency_ms=500,
            is_correct=False,
            timestamp=now - timedelta(days=1, seconds=-(i + 10)),
        )

    assert svc.check_weekly_accuracy(threshold=0.7) is True


@spec_ref("FS-AI-013", "AC-5")
async def test_fs_ai_013_ac5_accuracy_above_threshold():
    """FS-AI-013 AC-5: No alert when accuracy >= 70%."""
    svc = _make_service()
    now = datetime.now(timezone.utc)

    # 8 correct + 2 incorrect = 80% accuracy → above 70%
    for i in range(8):
        svc.record_llm_call(
            provider="openai", model="gpt-4o",
            prompt_tokens=100, completion_tokens=50, latency_ms=500,
            is_correct=True,
            timestamp=now - timedelta(hours=12, seconds=-i),
        )
    for i in range(2):
        svc.record_llm_call(
            provider="openai", model="gpt-4o",
            prompt_tokens=100, completion_tokens=50, latency_ms=500,
            is_correct=False,
            timestamp=now - timedelta(hours=12, seconds=-(i + 20)),
        )

    assert svc.check_weekly_accuracy(threshold=0.7) is False


@spec_ref("FS-AI-013", "AC-5")
async def test_fs_ai_013_ac5_no_feedback():
    """FS-AI-013 AC-5: No alert when no feedback records exist."""
    svc = _make_service()
    _seed_records(svc, count=5, is_correct=None)
    assert svc.check_weekly_accuracy(threshold=0.7) is False


# ---------------------------------------------------------------------------
# AC-6: AI Health dashboard schema validation (frontend is Vitest scope)
# ---------------------------------------------------------------------------


@spec_ref("FS-AI-013", "AC-6")
async def test_fs_ai_013_ac6_ai_health():
    """FS-AI-013 AC-6: Schema contains all fields needed for AI Health dashboard.

    Frontend visualization is validated via Vitest (separate scope).
    This test validates the backend contract (schema completeness).
    """
    svc = _make_service()
    _seed_records(svc, count=3, has_hallucination=False)
    _seed_records(svc, count=1, has_hallucination=True)

    summary = svc.get_summary()

    # Verify all dashboard-required fields exist
    assert hasattr(summary, "total_calls")
    assert hasattr(summary, "total_tokens")
    assert hasattr(summary, "avg_latency_ms")
    assert hasattr(summary, "total_cost")
    assert hasattr(summary, "hallucination_rate")
    assert hasattr(summary, "period_from")
    assert hasattr(summary, "period_to")

    # Verify JSON serialization works (frontend consumes JSON)
    json_data = summary.model_dump()
    assert isinstance(json_data["total_calls"], int)
    assert isinstance(json_data["avg_latency_ms"], float)
    assert isinstance(json_data["hallucination_rate"], float)


# ---------------------------------------------------------------------------
# AC-7: Model drift detection
# ---------------------------------------------------------------------------


@spec_ref("FS-AI-013", "AC-7")
async def test_fs_ai_013_ac7_model_drift_metrics():
    """FS-AI-013 AC-7: detect_model_drift identifies drift when patterns change."""
    svc = _make_service()
    now = datetime.now(timezone.utc)

    # Historical baseline: stable latency ~500ms, tokens ~300
    for i in range(20):
        svc.record_llm_call(
            provider="openai", model="gpt-4o",
            prompt_tokens=200, completion_tokens=100,
            latency_ms=500,
            timestamp=now - timedelta(hours=48, seconds=-i),
        )

    # Recent window: significantly higher latency ~2000ms, tokens ~800
    for i in range(10):
        svc.record_llm_call(
            provider="openai", model="gpt-4o",
            prompt_tokens=500, completion_tokens=300,
            latency_ms=2000,
            timestamp=now - timedelta(hours=6, seconds=-i),
        )

    result = svc.detect_model_drift(window_hours=24)

    assert isinstance(result, ModelDriftResult)
    assert result.drift_score > 0.3  # Should detect drift
    assert result.is_drifting is True
    assert len(result.details) > 0


@spec_ref("FS-AI-013", "AC-7")
async def test_fs_ai_013_ac7_no_drift():
    """FS-AI-013 AC-7: No drift when recent matches historical pattern."""
    svc = _make_service()
    now = datetime.now(timezone.utc)

    # All records have same pattern
    for i in range(30):
        svc.record_llm_call(
            provider="openai", model="gpt-4o",
            prompt_tokens=200, completion_tokens=100,
            latency_ms=500,
            timestamp=now - timedelta(hours=72 - i),
        )

    result = svc.detect_model_drift(window_hours=24)
    assert result.is_drifting is False
    assert result.drift_score <= 0.3


@spec_ref("FS-AI-013", "AC-7")
async def test_fs_ai_013_ac7_insufficient_data():
    """FS-AI-013 AC-7: Returns no-drift when insufficient data."""
    svc = _make_service()
    svc.record_llm_call(
        provider="openai", model="gpt-4o",
        prompt_tokens=100, completion_tokens=50, latency_ms=500,
    )

    result = svc.detect_model_drift(window_hours=24)
    assert result.is_drifting is False
    assert result.drift_score == 0.0
    assert "Insufficient" in result.details


@spec_ref("FS-AI-013", "AC-7")
async def test_fs_ai_013_ac7_drift_api_endpoint(client):
    """FS-AI-013 AC-7: GET /api/v1/llm-observability/drift returns valid JSON."""
    dep_key = _setup_auth_override()
    try:
        resp = await client.get("/api/v1/llm-observability/drift")
        assert resp.status_code == 200
        data = resp.json()
        assert "drift_score" in data
        assert "is_drifting" in data
        assert "details" in data
    finally:
        _teardown_auth_override(dep_key)
