# Spec: FS-KPI-001
"""Auto-generated test stubs for FS-KPI-001 Acceptance Criteria.

Generated by: uv run python -m scripts.gen_spec_tests
Strategy: TEST-STRATEGY-001

IMPORTANT: Implement each test stub by replacing pytest.skip() with real assertions.
Do NOT delete the @spec_ref decorator -- it enables AC tracking in CI.
"""

import pytest

from tests.conftest import spec_ref


@spec_ref("FS-KPI-001", "AC-1")
async def test_fs_kpi_001_ac1_get_api_v1_instances_id_kpi_12_kpi():
    """FS-KPI-001 AC-1: GET /api/v1/instances/{id}/kpi에서 12개 KPI가 모두 반환됨"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-KPI-001", "AC-2")
async def test_fs_kpi_001_ac2_tps_qps_deadlocks_delta():
    """FS-KPI-001 AC-2: TPS, QPS, Deadlocks는 delta/초 기반으로 계산됨"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-KPI-001", "AC-3")
async def test_fs_kpi_001_ac3_buffer_hit_ratio_delta():
    """FS-KPI-001 AC-3: Buffer Hit Ratio는 delta 기반 (누적 비율이 아님)"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-KPI-001", "AC-4")
async def test_fs_kpi_001_ac4_5_kpi_tps_hit_conn_locks_size():
    """FS-KPI-001 AC-4: 인스턴스 카드에 5개 핵심 KPI가 표시됨 (TPS, Hit%, Conn, Locks, Size)"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-KPI-001", "AC-5")
async def test_fs_kpi_001_ac5_kpi_overview_panel_12_kpi():
    """FS-KPI-001 AC-5: KPI Overview Panel이 인스턴스 선택 시 12개 전체 KPI 표시"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-KPI-001", "AC-6")
async def test_fs_kpi_001_ac6_normal_warning_critical():
    """FS-KPI-001 AC-6: 임계값에 따라 normal/warning/critical 색상 코딩"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-KPI-001", "AC-7")
async def test_fs_kpi_001_ac7_max_connections():
    """FS-KPI-001 AC-7: max_connections 대비 연결 사용률(%) 표시"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-KPI-001", "AC-8")
async def test_fs_kpi_001_ac8_pg_stat_statements_advisory_warning_create_extensi():
    """FS-KPI-001 AC-8: pg_stat_statements 미설치 시 advisory warning + CREATE EXTENSION SQL 안내"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-KPI-001", "AC-9")
async def test_fs_kpi_001_ac9_toast_info_8_warning_12():
    """FS-KPI-001 AC-9: Toast 알림이 화면 우상단에 표시되고 자동 닫힘 (info 8초, warning 12초)"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-KPI-001", "AC-10")
async def test_fs_kpi_001_ac10_notification_panel_advisory_sql_action():
    """FS-KPI-001 AC-10: Notification Panel에서 advisory 목록 확인 + SQL action 복사 가능"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-KPI-001", "AC-11")
async def test_fs_kpi_001_ac11():
    """FS-KPI-001 AC-11: 알림 벨에 미읽음 수 빨간 배지 표시"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")
