# Spec: FS-AI-LLM-001
"""Auto-generated test stubs for FS-AI-LLM-001 Acceptance Criteria.

Generated by: uv run python -m scripts.gen_spec_tests
Strategy: TEST-STRATEGY-001

IMPORTANT: Implement each test stub by replacing pytest.skip() with real assertions.
Do NOT delete the @spec_ref decorator -- it enables AC tracking in CI.
"""

import pytest

from tests.conftest import spec_ref


@spec_ref("FS-AI-LLM-001", "AC-1")
async def test_fs_ai_llm_001_ac1_get_api_v1_settings_llm():
    """FS-AI-LLM-001 AC-1: GET /api/v1/settings/llm에서 현재 프로바이더/모델 반환"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-AI-LLM-001", "AC-2")
async def test_fs_ai_llm_001_ac2_put_api_v1_settings_llm():
    """FS-AI-LLM-001 AC-2: PUT /api/v1/settings/llm으로 프로바이더/모델 변경 가능"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-AI-LLM-001", "AC-3")
async def test_fs_ai_llm_001_ac3_get_api_v1_settings_llm_ollama_models():
    """FS-AI-LLM-001 AC-3: GET /api/v1/settings/llm/ollama-models에서 로컬 모델 목록 반환"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-AI-LLM-001", "AC-4")
async def test_fs_ai_llm_001_ac4_4_ollama_openai_anthropic_google_langchain():
    """FS-AI-LLM-001 AC-4: 4개 프로바이더(Ollama/OpenAI/Anthropic/Google) LangChain 인스턴스 생성"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-AI-LLM-001", "AC-5")
async def test_fs_ai_llm_001_ac5_api_available_false():
    """FS-AI-LLM-001 AC-5: API 키 미설정 프로바이더는 available: false 반환"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-AI-LLM-001", "AC-6")
async def test_fs_ai_llm_001_ac6_nl2sql_mtl_lite_rag_llmprovidermanager_llm():
    """FS-AI-LLM-001 AC-6: NL2SQL, MTL Lite, RAG 서비스가 LLMProviderManager를 통해 LLM 호출"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-AI-LLM-001", "AC-7")
async def test_fs_ai_llm_001_ac7_post_api_v1_settings_llm_test():
    """FS-AI-LLM-001 AC-7: POST /api/v1/settings/llm/test로 선택 모델 테스트 가능"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")

@spec_ref("FS-AI-LLM-001", "AC-8")
async def test_fs_ai_llm_001_ac8_frontend_settings_api_ui():
    """FS-AI-LLM-001 AC-8: Frontend Settings에서 프로바이더/모델 선택 + API 키 입력 UI"""
    # TODO: Implement test -- auto-generated from Spec
    pytest.skip("Auto-generated stub -- implement test")
