# Spec: MVP-AI-001, MVP-AI-002
"""Baselines API -- query learned baselines and trigger manual retraining.

Endpoints per MVP.md Section 4.8:
  GET  /instances/{id}/baselines        -- list baselines for instance
  POST /instances/{id}/baselines/retrain -- trigger manual retrain
"""

from uuid import UUID

import structlog
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_session
from app.models.baseline import Baseline
from app.models.db_instance import DBInstance
from app.schemas.baseline import (
    BaselineListResponse,
    BaselineResponse,
    BaselineRetrainResponse,
)

logger = structlog.get_logger(__name__)

router = APIRouter()


async def _verify_instance(session: AsyncSession, instance_id: UUID) -> DBInstance:
    """Verify instance exists and is not deleted. Raises 404 if not found."""
    stmt = select(DBInstance).where(
        DBInstance.id == instance_id,
        DBInstance.deleted_at.is_(None),
    )
    result = await session.execute(stmt)
    instance = result.scalar_one_or_none()
    if instance is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Instance {instance_id} not found. Use GET /api/v1/instances to list available instances.",
        )
    return instance


@router.get(
    "/instances/{instance_id}/baselines",
    response_model=BaselineListResponse,
)
async def list_baselines(
    instance_id: UUID,
    metric_type: str | None = Query(default=None, description="Filter by metric type"),
    time_bucket: str | None = Query(
        default=None,
        pattern=r"^(weekday_business|weekday_night|weekend)$",
        description="Filter by time bucket",
    ),
    active_only: bool = Query(default=True, description="Only active baselines"),
    session: AsyncSession = Depends(get_session),
) -> BaselineListResponse:
    """List baselines for a DB instance.

    Spec: MVP-AI-001 -- baselines are auto-generated by STL + Isolation Forest.
    """
    await _verify_instance(session, instance_id)

    stmt = select(Baseline).where(Baseline.instance_id == instance_id)

    if active_only:
        stmt = stmt.where(Baseline.is_active.is_(True))
    if metric_type is not None:
        stmt = stmt.where(Baseline.metric_type == metric_type)
    if time_bucket is not None:
        stmt = stmt.where(Baseline.time_bucket == time_bucket)

    stmt = stmt.order_by(Baseline.metric_type, Baseline.time_bucket)

    # Count
    count_stmt = select(func.count()).select_from(stmt.subquery())
    count_result = await session.execute(count_stmt)
    total = count_result.scalar_one()

    # Fetch
    result = await session.execute(stmt)
    baselines = list(result.scalars().all())

    return BaselineListResponse(
        items=[BaselineResponse.model_validate(b) for b in baselines],
        total=total,
    )


@router.post(
    "/instances/{instance_id}/baselines/retrain",
    response_model=BaselineRetrainResponse,
    status_code=status.HTTP_202_ACCEPTED,
)
async def trigger_retrain(
    instance_id: UUID,
    session: AsyncSession = Depends(get_session),
) -> BaselineRetrainResponse:
    """Trigger manual baseline retraining for an instance.

    Dispatches an async Celery task. The response returns immediately
    with a 202 Accepted and the task ID for tracking.

    Spec: MVP-AI-001 -- manual retrain endpoint.
    """
    instance = await _verify_instance(session, instance_id)

    from app.tasks.analyze import retrain_baselines

    # Dispatch async retrain -- the task retrains all instances,
    # but we log which instance triggered it.
    result = retrain_baselines.delay()

    logger.info(
        "baselines.retrain_triggered",
        instance_id=str(instance_id),
        instance_name=instance.name,
        task_id=result.id if result else None,
    )

    return BaselineRetrainResponse(
        message=f"Baseline retrain triggered for instance '{instance.name}'. "
        "This runs asynchronously and may take several minutes.",
        instance_id=instance_id,
        task_id=result.id if result else None,
    )
